### ISSUE TITLE
Refactor to use Streams instead of Events

### ISSUE THREAD

**Issue by nelsonsilva** [nelsonsilva/sockjs-dart-client#2]
We should refactor the client to use Streams / StreamControllers instead of Events.

**Comment by nelsonsilva** [comment]
Done in https://github.com/nelsonsilva/sockjs-dart-client/commit/8cba48df75ffdf27acb9e62124078db11958fb7d

**Comment by nelsonsilva** [comment]
@sdeleuze Can you try this to see if everything still works for you ?

**Comment by sdeleuze** [comment]
It worked with websocket but not with xhr-streaming, I have submitted a fix :
https://github.com/nelsonsilva/sockjs-dart-client/pull/5

**Comment by sdeleuze** [comment]
Since the fix has been merged, I think this issue can be closed
