### ISSUE TITLE
Publish to pub

### ISSUE THREAD

**Issue by nelsonsilva** [nelsonsilva/sockjs-dart-client#4]
Must publish this to pub

**Comment by wienczny** [comment]
Do you need help to publish this package to pub?

**Comment by tomikiss** [comment]
Do you need any help with this? I would like to depend on this so it would make a lots of difference for me. Could you include a license file as well?

**Comment by nelsonsilva** [comment]
@wienczny @tomikiss Sorry for the delay. Just published this to pub.
